import routes from "./routes.json";

// Generated by scripts/generate-routes.mjs (runs before `next build`).
const valid = new Set<string>(routes as string[]);

/** True if `href` is an internal path that maps to a real, generated route. */
export function isValidRoute(href: string | undefined | null): boolean {
  if (!href) return false;
  let p = href.split(/[?#]/)[0];
  if (p.length > 1 && p.endsWith("/")) p = p.slice(0, -1);
  return valid.has(p) || valid.has(p + "/");
}

/** Every generated route path (e.g. "/", "/about", ...). Used by the sitemap. */
export function getAllRoutes(): string[] {
  return routes as string[];
}
